config/routes.rb
Rails.application.routes.draw do
  resources :gather_informations
  resources :move_armies
  resources :raise_armies
  resources :path_to_power_constructions
  resources :resource_generator_constructions
  resources :trade_request_responses
  resources :fund_request_responses
  resources :funding_request_resources
  resources :funding_request_player_roles
  resources :funding_requests
  resources :fundings
  resources :constructions
  resources :player_military_unit_roles
  resources :military_units
  resources :resource_generators
  resources :trade_player_roles, only: [:index,:show,:edit,:update,:destroy]
  resources :trade_request_resources
  resources :trade_requests do
    resources :trade_player_roles, only:[:index,:new,:create]
  end
  resources :player_loyalty_roles
  resources :player_loyalties
  resources :player_actions
  resources :player_resources
  resources :rounds
  resources :player_match_roles
  resources :matches
  resources :players
  resources :games
  resources :results_pages
  resources :gathered_information

  get 'sign_up', to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "login", to: "login#new"
  post "login", to: "login#create"
  get "logout", to:"login#destroy"

  get 'game_page/new', to: "game_page#new"
  get 'game_pages',to: "game_page#index"
  post 'game_page/show', to: "game_page#show"
  get 'game_page/show', to:"game_page#show"
  get 'leave_game_page',to: 'game_page#leave_game_page'

  get 'end_round',to:'rounds#end_round'
  get 'rescind_end_round',to:'rounds#rescind_end_round'

  post "take_action",to:"player_actions#new"
  post "player_action_raise_army", to: "player_actions#create_raise_army_action"
  get "/player_actions_move_army", to: "player_actions#move_army"

  post "/trade_requests/new", to: "trade_requests#new"

  get "/move_army", to:"move_armies#new"

  get "results_pages/results_page", to:"results_pages#show"
  get "how_to_play", to:"main#how_to_play"
  root to:"main#index"
end

app/models/funding_request_resource.rb
class FundingRequestResource < ApplicationRecord
  belongs_to :funding_request
  validates_uniqueness_of :funding_resource_type, scope:[:funding_request]
end

app/controllers/funding_request_resources_controller.rb
class FundingRequestResourcesController < ApplicationController
  before_action :set_funding_request_resource, only: %i[ show edit update destroy ]
  before_action :is_admin, only:[:index,:show,:new,:edit,:create,:update,:destroy]
  before_action :logged_in?, only:[:index,:show,:new,:edit,:create,:update,:destroy]
  # GET /funding_request_resources or /funding_request_resources.json
  def index
    @funding_request_resources = FundingRequestResource.all
  end

  # GET /funding_request_resources/1 or /funding_request_resources/1.json
  def show
  end

  # GET /funding_request_resources/new
  def new
    @funding_request_resource = FundingRequestResource.new
  end

  # GET /funding_request_resources/1/edit
  def edit
  end

  # POST /funding_request_resources or /funding_request_resources.json
  def create
    @funding_request_resource = FundingRequestResource.new(funding_request_resource_params)

    respond_to do |format|
      if @funding_request_resource.save
        format.html { redirect_to funding_request_resource_url(@funding_request_resource), notice: "Funding request resource was successfully created." }
        format.json { render :show, status: :created, location: @funding_request_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funding_request_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funding_request_resources/1 or /funding_request_resources/1.json
  def update
    respond_to do |format|
      if @funding_request_resource.update(funding_request_resource_params)
        format.html { redirect_to funding_request_resource_url(@funding_request_resource), notice: "Funding request resource was successfully updated." }
        format.json { render :show, status: :ok, location: @funding_request_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funding_request_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funding_request_resources/1 or /funding_request_resources/1.json
  def destroy
    @funding_request_resource.destroy

    respond_to do |format|
      format.html { redirect_to funding_request_resources_url, notice: "Funding request resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funding_request_resource
      @funding_request_resource = FundingRequestResource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funding_request_resource_params
      params.require(:funding_request_resource).permit(:funding_request_id, :funding_resource_type, :funding_resource_amount)
    end
end

app/helpers/funding_request_resources_helper.rb
module FundingRequestResourcesHelper
end

app/views/funding_request_resources/_form.html.erb
<%= form_with(model: funding_request_resource) do |form| %>
  <% if funding_request_resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funding_request_resource.errors.count, "error") %> prohibited this funding_request_resource from being saved:</h2>

      <ul>
        <% funding_request_resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :funding_request_id, style: "display: block" %>
    <%= form.text_field :funding_request_id %>
  </div>

  <div>
    <%= form.label :funding_resource_type, style: "display: block" %>
    <%= form.text_field :funding_resource_type %>
  </div>

  <div>
    <%= form.label :funding_resource_amount, style: "display: block" %>
    <%= form.number_field :funding_resource_amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funding_request_resources/_funding_request_resource.html.erb
<div id="<%= dom_id funding_request_resource %>" class="text-xl">
<%@test=funding_request_resource%>

  <%case funding_request_resource.funding_resource_type%>
    <%when "gold"%>
     <p class="border-4 border-black rounded-lg text-xl bg-gradient-to-b from-yellow-300 to-yellow-500 m-2">
        <%= funding_request_resource.funding_resource_type.capitalize %>:
        <%= funding_request_resource.funding_resource_amount %>
      </p>
    <%when "soldier"%>
      <p class="border-4 border-black rounded-lg text-xl bg-gradient-to-b from-red-300 to-red-500 m-2">
        <%= funding_request_resource.funding_resource_type.capitalize %>:
        <%= funding_request_resource.funding_resource_amount %>
      </p>
    <%when "spy"%>
      <p class="border-4 border-black rounded-lg text-xl bg-gradient-to-b from-stone-200 to-stone-400 m-2">
        <%= funding_request_resource.funding_resource_type.capitalize %>:
        <%= funding_request_resource.funding_resource_amount %>
      </p>
    <%else%>
      <p class="border-4 border-black rounded-lg text-xl bg-gradient-to-b from-yellow-300 to-yellow-500 m-2">
        <%= funding_request_resource.funding_resource_type.capitalize %>:
        <%= funding_request_resource.funding_resource_amount %>
      </p>
  <%end%>
  
   
</div>

app/views/funding_request_resources/edit.html.erb
<h1>Editing funding request resource</h1>

<%= render "form", funding_request_resource: @funding_request_resource %>

<br>

<div>
  <%= link_to "Show this funding request resource", @funding_request_resource %> |
  <%= link_to "Back to funding request resources", funding_request_resources_path %>
</div>

app/views/funding_request_resources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Funding request resources</h1>

<div id="funding_request_resources">
  <% @funding_request_resources.each do |funding_request_resource| %>
    <%= render funding_request_resource %>
    <p>
      <%= link_to "Show this funding request resource", funding_request_resource %>
    </p>
  <% end %>
</div>

<%= link_to "New funding request resource", new_funding_request_resource_path %>

app/views/funding_request_resources/new.html.erb
<h1>New funding request resource</h1>

<%= render "form", funding_request_resource: @funding_request_resource %>

<br>

<div>
  <%= link_to "Back to funding request resources", funding_request_resources_path %>
</div>

app/views/funding_request_resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @funding_request_resource %>

<div>
  <%= link_to "Edit this funding request resource", edit_funding_request_resource_path(@funding_request_resource) %> |
  <%= link_to "Back to funding request resources", funding_request_resources_path %>

  <%= button_to "Destroy this funding request resource", @funding_request_resource, method: :delete %>
</div>