config/routes.rb
Rails.application.routes.draw do
  resources :gather_informations
  resources :move_armies
  resources :raise_armies
  resources :path_to_power_constructions
  resources :resource_generator_constructions
  resources :trade_request_responses
  resources :fund_request_responses
  resources :funding_request_resources
  resources :funding_request_player_roles
  resources :funding_requests
  resources :fundings
  resources :constructions
  resources :player_military_unit_roles
  resources :military_units
  resources :resource_generators
  resources :trade_player_roles, only: [:index,:show,:edit,:update,:destroy]
  resources :trade_request_resources
  resources :trade_requests do
    resources :trade_player_roles, only:[:index,:new,:create]
  end
  resources :player_loyalty_roles
  resources :player_loyalties
  resources :player_actions
  resources :player_resources
  resources :rounds
  resources :player_match_roles
  resources :matches
  resources :players
  resources :games
  resources :results_pages
  resources :gathered_information

  get 'sign_up', to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "login", to: "login#new"
  post "login", to: "login#create"
  get "logout", to:"login#destroy"

  get 'game_page/new', to: "game_page#new"
  get 'game_pages',to: "game_page#index"
  post 'game_page/show', to: "game_page#show"
  get 'game_page/show', to:"game_page#show"
  get 'leave_game_page',to: 'game_page#leave_game_page'

  get 'end_round',to:'rounds#end_round'
  get 'rescind_end_round',to:'rounds#rescind_end_round'

  post "take_action",to:"player_actions#new"
  post "player_action_raise_army", to: "player_actions#create_raise_army_action"
  get "/player_actions_move_army", to: "player_actions#move_army"

  post "/trade_requests/new", to: "trade_requests#new"

  get "/move_army", to:"move_armies#new"

  get "results_pages/results_page", to:"results_pages#show"
  get "how_to_play", to:"main#how_to_play"
  root to:"main#index"
end

app/controllers/player_actions_controller.rb
class PlayerActionsController < ApplicationController
  before_action :set_player_action, only: %i[ show edit update destroy ]
  before_action :set_game,only:[:index,:new,:create,:create_raise_army_action,:move_army]
  before_action :set_user,only:[:index,:new,:create,:create_raise_army_action,:move_army]
  before_action :set_player,only:[:index,:new,:create,:create_raise_army_action,:move_army]
  before_action :logged_in?, only:[:index,:show,:new,:edit,:create,:update,:destroy]
  before_action :is_admin?, only:[:show,:new,:edit,:update,:destroy]
  # GET /player_actions or /player_actions.json
  def index
    @player_action=PlayerAction.new()
    @round=@game.matches.last.rounds.last
  end

  # GET /player_actions/1 or /player_actions/1.json
  def show
  end

  # GET /player_actions/new
  def new
    @player_action = PlayerAction.new
    
    render :new, status: 422
  end

  # GET /player_actions/1/edit
  def edit
  end

  # POST /player_actions or /player_actions.json
  def create
    @player_action = PlayerAction.new(player:@player,round:@game.matches.last.rounds.last,action_type:"gathered_information")
    if player_action_params[:type_of_information]
      @gathered_information=GatherInformation.new(player_action:@player_action,information_type:player_action_params[:type_of_information])
      respond_to do |format|
        if @player_action.save && @gathered_information.save
          format.html { redirect_to gather_information_url(@gather_information), notice: "Player action was successfully created." }
        else
          format.html { redirect_to game_page_show_path,notice:"Failed to gather info" }
        
        end
      end
    end
  end

  
  def create_raise_army_action
    
    @player_action=PlayerAction.new(action_type:"raise_army,", player:@player, round:@game.matches.last.rounds.last)
    if @player_action.save
      redirect_to url_from("/raise_army"), action: "create"
    end

  end
  def move_army
  
      redirect_to url_from("/move_army"), action: "new"
   
  end

  # PATCH/PUT /player_actions/1 or /player_actions/1.json
  def update
    respond_to do |format|
      if @player_action.update(player_action_params)
        format.html { redirect_to player_action_url(@player_action), notice: "Player action was successfully updated." }
        format.json { render :show, status: :ok, location: @player_action }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_actions/1 or /player_actions/1.json
  def destroy
    @player_action.destroy

    respond_to do |format|
      format.html { redirect_to player_actions_url, notice: "Player action was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_action
      @player_action = PlayerAction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

    def player_action_params
      params.require(:player_action).permit(:type_of_information)
    end
end

app/helpers/player_actions_helper.rb
module PlayerActionsHelper
end

app/views/player_actions/index.html.erb
<div class="container mx-auto h-screen w-screen max-w-2xl text-center">
    <div class="grid grid-cols-1 gap-1 text-center m-2">
        <span class="text-lg underline">Player actions</span>
        <%if @player.has_raised_army_this_round?%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You have already raised an army this round.</p>
        <%elsif @player.player_resources&.where(resource_type:"soldier").count>0%>
            <%= link_to "Raise Military Unit"  , new_raise_army_path,class:"bg-gradient-to-b from-indigo-300 to-indigo-500 border-4 border-black rounded-lg text-center text-lg" %>
        <%else%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You need soldiers to raise armies.</p>
        <%end%>
        <%if @player.has_gathered_information_this_round?%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You have gathered information this round.</p>
        <%elsif @player.game.players.count>1%>
            <%= link_to "Gather Information",  new_gather_information_path, class:"bg-gradient-to-b from-indigo-300 to-indigo-500 border-4 border-black rounded-lg text-center text-lg" %>
        <%else%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You need another player to gather information on.</p>
        <%end%>
        <%if @player.has_moved_a_military_unit_this_round?%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">Already moved a military unit this round.</p>
        <%elsif @player.has_military_units?%>
            <%= link_to "Command Military Unit"  , new_move_army_path, class:"bg-gradient-to-b from-indigo-300 to-indigo-500 border-4 border-black rounded-lg text-center text-lg" %>
        <%else%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You have no military units to move.</p>
        <%end%>
        <%if @round.constructions.exists?(player:@player)%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">Construction already made this round.</p>
        <%else%>
            <%= link_to "Create Construction", new_construction_path,class:"bg-gradient-to-b from-indigo-300 to-indigo-500 border-4 border-black rounded-lg text-center text-lg" %>
        <%end%>
        <%if @player.has_unfunded_constructions?%>
            <%if @player.can_ask_for_funding?%>
                <%= link_to "Request Funding for a Construction", new_funding_request_path,class:"bg-gradient-to-b from-indigo-300 to-indigo-500 border-4 border-black rounded-lg text-center text-lg" %>
            <%else%>
                <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You have knocked on every door my lord.</p>
            <%end%>
        <%else%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You have no constructions to fund my lord!</p>
        <%end%>
        <%if @player.own_trade_requests_this_round.count>=3%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You already have three trades made or pending.</p>
        <%elsif @player.game.players.count>1%>
            <%= link_to "Request Trade", new_trade_request_path,class:"bg-gradient-to-b from-indigo-300 to-indigo-500 border-4 border-black rounded-lg text-center text-lg" %>
        <%else%>
            <p class="bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-lg hover:bg-gray-700 hover:text-red-500">You need another player to trade with.</p>
        <%end%>
        <%= link_to "Return to Games Page", game_page_show_path(), class:"bg-gradient-to-b from-rose-300 to-rose-500  border-4 border-black rounded-lg text-xl m-4 p-2"%><br/>
    </div>
</div>

app/views/player_actions/show.html.erb
<div class="flex flex-col text-center justify-center m-8">
  <h1 class="text-4xl underline underline-offset-4 m-8">You have Learned that</h1><br/>
    <div class="m-4">
        
    </div>

<div class="m-4">
   <%= link_to "Main Page (NO RETURNING!)", game_page_show_path, class:"bg-teal-200 border-4 border-black rounded-lg p-3 m-2" %>
</div>
</div>