config/routes.rb
Rails.application.routes.draw do
  resources :gather_informations
  resources :move_armies
  resources :raise_armies
  resources :path_to_power_constructions
  resources :resource_generator_constructions
  resources :trade_request_responses
  resources :fund_request_responses
  resources :funding_request_resources
  resources :funding_request_player_roles
  resources :funding_requests
  resources :fundings
  resources :constructions
  resources :player_military_unit_roles
  resources :military_units
  resources :resource_generators
  resources :trade_player_roles, only: [:index,:show,:edit,:update,:destroy]
  resources :trade_request_resources
  resources :trade_requests do
    resources :trade_player_roles, only:[:index,:new,:create]
  end
  resources :player_loyalty_roles
  resources :player_loyalties
  resources :player_actions
  resources :player_resources
  resources :rounds
  resources :player_match_roles
  resources :matches
  resources :players
  resources :games
  resources :results_pages
  resources :gathered_information

  get 'sign_up', to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "login", to: "login#new"
  post "login", to: "login#create"
  get "logout", to:"login#destroy"

  get 'game_page/new', to: "game_page#new"
  get 'game_pages',to: "game_page#index"
  post 'game_page/show', to: "game_page#show"
  get 'game_page/show', to:"game_page#show"
  get 'leave_game_page',to: 'game_page#leave_game_page'

  get 'end_round',to:'rounds#end_round'
  get 'rescind_end_round',to:'rounds#rescind_end_round'

  post "take_action",to:"player_actions#new"
  post "player_action_raise_army", to: "player_actions#create_raise_army_action"
  get "/player_actions_move_army", to: "player_actions#move_army"

  post "/trade_requests/new", to: "trade_requests#new"

  get "/move_army", to:"move_armies#new"

  get "results_pages/results_page", to:"results_pages#show"
  get "how_to_play", to:"main#how_to_play"
  root to:"main#index"
end

app/models/player_match_role.rb
class PlayerMatchRole < ApplicationRecord
  belongs_to :match
  belongs_to :player
end

app/controllers/player_match_roles_controller.rb
class PlayerMatchRolesController < ApplicationController
  before_action :set_player_match_role, only: %i[ show edit update destroy ]
  before_action :logged_in?, only:[:index,:show,:new,:edit,:create,:update,:destroy]
  before_action :is_admin?, only:[:index,:show,:new,:edit,:create,:update,:destroy]
  # GET /player_match_roles or /player_match_roles.json
  def index
    @player_match_roles = PlayerMatchRole.all
  end

  # GET /player_match_roles/1 or /player_match_roles/1.json
  def show
  end

  # GET /player_match_roles/new
  def new
    @player_match_role = PlayerMatchRole.new
  end

  # GET /player_match_roles/1/edit
  def edit
  end

  # POST /player_match_roles or /player_match_roles.json
  def create
    @player_match_role = PlayerMatchRole.new(player_match_role_params)

    respond_to do |format|
      if @player_match_role.save
        format.html { redirect_to player_match_role_url(@player_match_role), notice: "Player match role was successfully created." }
        format.json { render :show, status: :created, location: @player_match_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player_match_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_match_roles/1 or /player_match_roles/1.json
  def update
    respond_to do |format|
      if @player_match_role.update(player_match_role_params)
        format.html { redirect_to player_match_role_url(@player_match_role), notice: "Player match role was successfully updated." }
        format.json { render :show, status: :ok, location: @player_match_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player_match_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_match_roles/1 or /player_match_roles/1.json
  def destroy
    @player_match_role.destroy

    respond_to do |format|
      format.html { redirect_to player_match_roles_url, notice: "Player match role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_match_role
      @player_match_role = PlayerMatchRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_match_role_params
      params.require(:player_match_role).permit(:match_id, :player_id, :player_match_role_type)
    end
end

app/helpers/player_match_roles_helper.rb
module PlayerMatchRolesHelper
end

app/views/player_match_roles/_form.html.erb
<%= form_with(model: player_match_role) do |form| %>
  <% if player_match_role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player_match_role.errors.count, "error") %> prohibited this player_match_role from being saved:</h2>

      <ul>
        <% player_match_role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :match_id, style: "display: block" %>
    <%= form.text_field :match_id %>
  </div>

  <div>
    <%= form.label :player_id, style: "display: block" %>
    <%= form.text_field :player_id %>
  </div>

  <div>
    <%= form.label :player_match_role_type, style: "display: block" %>
    <%= form.text_field :player_match_role_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/player_match_roles/_player_match_role.html.erb
<div id="<%= dom_id player_match_role %>">
  <p>
    <strong>Match:</strong>
    <%= player_match_role.match_id %>
  </p>

  <p>
    <strong>Player:</strong>
    <%= player_match_role.player_id %>
  </p>

  <p>
    <strong>Player match role type:</strong>
    <%= player_match_role.player_match_role_type %>
  </p>

</div>

app/views/player_match_roles/edit.html.erb
<h1>Editing player match role</h1>

<%= render "form", player_match_role: @player_match_role %>

<br>

<div>
  <%= link_to "Show this player match role", @player_match_role %> |
  <%= link_to "Back to player match roles", player_match_roles_path %>
</div>

app/views/player_match_roles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Player match roles</h1>

<div id="player_match_roles">
  <% @player_match_roles.each do |player_match_role| %>
    <%= render player_match_role %>
    <p>
      <%= link_to "Show this player match role", player_match_role %>
    </p>
  <% end %>
</div>

<%= link_to "New player match role", new_player_match_role_path %>

app/views/player_match_roles/new.html.erb
<h1>New player match role</h1>

<%= render "form", player_match_role: @player_match_role %>

<br>

<div>
  <%= link_to "Back to player match roles", player_match_roles_path %>
</div>

app/views/player_match_roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player_match_role %>

<div>
  <%= link_to "Edit this player match role", edit_player_match_role_path(@player_match_role) %> |
  <%= link_to "Back to player match roles", player_match_roles_path %>

  <%= button_to "Destroy this player match role", @player_match_role, method: :delete %>
</div>