config/routes.rb
Rails.application.routes.draw do
  resources :gather_informations
  resources :move_armies
  resources :raise_armies
  resources :path_to_power_constructions
  resources :resource_generator_constructions
  resources :trade_request_responses
  resources :fund_request_responses
  resources :funding_request_resources
  resources :funding_request_player_roles
  resources :funding_requests
  resources :fundings
  resources :constructions
  resources :player_military_unit_roles
  resources :military_units
  resources :resource_generators
  resources :trade_player_roles, only: [:index,:show,:edit,:update,:destroy]
  resources :trade_request_resources
  resources :trade_requests do
    resources :trade_player_roles, only:[:index,:new,:create]
  end
  resources :player_loyalty_roles
  resources :player_loyalties
  resources :player_actions
  resources :player_resources
  resources :rounds
  resources :player_match_roles
  resources :matches
  resources :players
  resources :games
  resources :results_pages
  resources :gathered_information

  get 'sign_up', to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "login", to: "login#new"
  post "login", to: "login#create"
  get "logout", to:"login#destroy"

  get 'game_page/new', to: "game_page#new"
  get 'game_pages',to: "game_page#index"
  post 'game_page/show', to: "game_page#show"
  get 'game_page/show', to:"game_page#show"
  get 'leave_game_page',to: 'game_page#leave_game_page'

  get 'end_round',to:'rounds#end_round'
  get 'rescind_end_round',to:'rounds#rescind_end_round'

  post "take_action",to:"player_actions#new"
  post "player_action_raise_army", to: "player_actions#create_raise_army_action"
  get "/player_actions_move_army", to: "player_actions#move_army"

  post "/trade_requests/new", to: "trade_requests#new"

  get "/move_army", to:"move_armies#new"

  get "results_pages/results_page", to:"results_pages#show"
  get "how_to_play", to:"main#how_to_play"
  root to:"main#index"
end

app/models/player_military_unit_role.rb
class PlayerMilitaryUnitRole < ApplicationRecord
  belongs_to :player
  belongs_to :military_unit
end

app/controllers/player_military_unit_roles_controller.rb
class PlayerMilitaryUnitRolesController < ApplicationController
  before_action :set_player_military_unit_role, only: %i[ show edit update destroy ]
  before_action :set_player, only:[:index]
  before_action :set_game,onyl:[:index]
  before_action :logged_in?, only:[:index,:show,:new,:edit,:create,:update,:destroy]
  before_action :is_admin?, only:[:show,:new,:edit,:create,:update,:destroy]
  # GET /player_military_unit_roles or /player_military_unit_roles.json
  def index
    @player_military_unit_roles = @player.player_military_unit_roles
    @round=@game.matches.last.rounds.last
  end

  # GET /player_military_unit_roles/1 or /player_military_unit_roles/1.json
  def show
  end

  # GET /player_military_unit_roles/new
  def new
    @player_military_unit_role = PlayerMilitaryUnitRole.new
  end

  # GET /player_military_unit_roles/1/edit
  def edit
  end

  # POST /player_military_unit_roles or /player_military_unit_roles.json
  def create
    @player_military_unit_role = PlayerMilitaryUnitRole.new(player_military_unit_role_params)

    respond_to do |format|
      if @player_military_unit_role.save
        format.html { redirect_to player_military_unit_role_url(@player_military_unit_role), notice: "Player military unit role was successfully created." }
        format.json { render :show, status: :created, location: @player_military_unit_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player_military_unit_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_military_unit_roles/1 or /player_military_unit_roles/1.json
  def update
    respond_to do |format|
      if @player_military_unit_role.update(player_military_unit_role_params)
        format.html { redirect_to player_military_unit_role_url(@player_military_unit_role), notice: "Player military unit role was successfully updated." }
        format.json { render :show, status: :ok, location: @player_military_unit_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player_military_unit_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_military_unit_roles/1 or /player_military_unit_roles/1.json
  def destroy
    @player_military_unit_role.destroy

    respond_to do |format|
      format.html { redirect_to player_military_unit_roles_url, notice: "Player military unit role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_military_unit_role
      @player_military_unit_role = PlayerMilitaryUnitRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_military_unit_role_params
      params.require(:player_military_unit_role).permit(:player_id, :military_unit_id, :military_unit_role_type)
    end
end

app/helpers/player_military_unit_roles_helper.rb
module PlayerMilitaryUnitRolesHelper
end

app/views/player_military_unit_roles/_form.html.erb
<%= form_with(model: player_military_unit_role) do |form| %>
  <% if player_military_unit_role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player_military_unit_role.errors.count, "error") %> prohibited this player_military_unit_role from being saved:</h2>

      <ul>
        <% player_military_unit_role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :player_id, style: "display: block" %>
    <%= form.text_field :player_id %>
  </div>

  <div>
    <%= form.label :military_unit_id, style: "display: block" %>
    <%= form.text_field :military_unit_id %>
  </div>

  <div>
    <%= form.label :military_unit_role_type, style: "display: block" %>
    <%= form.text_field :military_unit_role_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/player_military_unit_roles/_player_military_unit_role.html.erb
<div id="<%= dom_id player_military_unit_role %>">
  <p>
    <strong>Player:</strong>
    <%= player_military_unit_role.player_id %>
  </p>

  <p>
    <strong>Military unit:</strong>
    <%= player_military_unit_role.military_unit_id %>
  </p>

  <p>
    <strong>Military unit role type:</strong>
    <%= player_military_unit_role.military_unit_role_type %>
  </p>

</div>

app/views/player_military_unit_roles/edit.html.erb
<h1>Editing player military unit role</h1>

<%= render "form", player_military_unit_role: @player_military_unit_role %>

<br>

<div>
  <%= link_to "Show this player military unit role", @player_military_unit_role %> |
  <%= link_to "Back to player military unit roles", player_military_unit_roles_path %>
</div>

app/views/player_military_unit_roles/index.html.erb
<%# Boolean and Arrays of military units %>
<%@your_lands_have_units=false%>
<%@other_lands_have_your_units=false%>
<%@you_have_units_being_raised=false%>
<%@units_on_your_lands=[]%>
<%@units_on_other_lands=[]%>
<%@units_being_raised_next_turn=[]%>

<%# Pushes your units on your land into the  units_on_your_land array %>
<%@player_military_unit_roles&.each do |player_military_unit_role|%> 
    <%if player_military_unit_role.military_unit_role_type=="houser" && player_military_unit_role.military_unit.owner==@player%>
        <%@units_on_your_lands.push(player_military_unit_role.military_unit)%>
        <%@your_lands_have_units=true%>
    <%end%> 
<%end%>

<%# Pushes others units on your land into the  units_on_your_land array %>
<%@player_military_unit_roles&.each do |player_military_unit_role|%> 
    <%if player_military_unit_role.military_unit_role_type=="houser" && player_military_unit_role.military_unit.owner!=@player%>
        <%@units_on_your_lands.push(player_military_unit_role.military_unit)%>
        <%@your_lands_have_units=true%>
    <%end%>  
<%end%>

<%# Pushes your units on other players lands into the units_on_other_lands array %>
<%@player.player_military_unit_roles&.each do |player_military_unit_role|%> 
    <%if player_military_unit_role.military_unit_role_type=="owner" && player_military_unit_role.military_unit.houser != @player%>
        <%@units_on_other_lands.push(player_military_unit_role.military_unit)%>
        <%@other_lands_have_your_units=true%>
          
    <%end%>  
<%end%> 

<%# Pushes the military units you are going to raise next round into the units being raised next turn array.%>
<%@player.player_actions&.each do |action|%> 
    <%if action.action_type=="raise_army" && action.round == @round%>
        <%@units_being_raised_next_turn.push(action.raise_armies.first)%> 
        <%@you_have_units_being_raised=true%>
    <%end%>  
<%end%>    

<div class="container mx-auto h-screen w-screen max-w-2xl text-center">
    <%# Shows Units on your lands if you have any and a message if you dont.%>
    <div class="text-center grid grid-cols-1 gap-1">
        <p class="text-xl underline underline-offset-4 text-center">Units on your lands</p>
        <%if @your_lands_have_units%>
            <p class="text-xl underline underline-offset-4 text-center">Units on <%=@player.house_name%> Lands</p>
            <%if !@player.is_not_routed%>
                <p class="text-xl underline bg-red-500 border-2 rounded-lg border-black p-1"> "YOU ARE ROUTED!" </p>
            <%end%>
            <%@units_on_your_lands.each do |local_military_unit|%>
                <%=render partial:"military_units/military_unit",locals:{military_unit:local_military_unit}%>
            <%end%>
        <%else%>
            <p class="bg-gradient-to-b from-red-100 to-red-300 border-4 border-black rounded-lg text-center text-lg">No units are on your lands.</p>
        <%end%>
    </div>
   
    <%# Shows your units on other lands if you have any and a message if you dont.%>
    <div class="text-center grid grid-cols-1 gap-1">
        <p class="text-xl underline underline-offset-4">Your Units on other lands</p>
        <%if @other_lands_have_your_units%>
            <%@units_on_other_lands.each do |away_military_unit|%>
                <%=render partial:"military_units/military_unit",locals:{military_unit:away_military_unit}%>
            <%end%>
        <%else%>
            <p class="bg-gradient-to-b from-red-100 to-red-300 border-4 border-black rounded-lg text-center text-lg">You have no units on other lands.</p>
        <%end%>
    </div>

    <%# Shows your units on other lands if you have any and a message if you dont.%>
    <div class="text-center grid grid-cols-1 gap-1">
        <p class="text-xl underline underline-offset-4 text-center">Units being raised next turn</p>
        <%if @you_have_units_being_raised%>
            <%@units_being_raised_next_turn.each do |raise_army|%>
                <%=render partial:"raise_armies/raise_army",locals:{raise_army: raise_army}%>
            <%end%>
        <%else%>
            <p class="bg-gradient-to-b from-red-100 to-red-300 border-4 border-black rounded-lg text-center text-lg">No units currently being raised.</p>
        <%end%>    
    </div><br/>
    <%= link_to "Return to Games Page", game_page_show_path(), class:"bg-gradient-to-b from-red-300 to-red-500 border-4 border-black rounded-lg text-xl"%><br/>

</div>          

app/views/player_military_unit_roles/new.html.erb
<h1>New player military unit role</h1>

<%= render "form", player_military_unit_role: @player_military_unit_role %>

<br>

<div>
  <%= link_to "Back to player military unit roles", player_military_unit_roles_path %>
</div>

app/views/player_military_unit_roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player_military_unit_role %>

<div>
  <%= link_to "Edit this player military unit role", edit_player_military_unit_role_path(@player_military_unit_role) %> |
  <%= link_to "Back to player military unit roles", player_military_unit_roles_path %>

  <%= button_to "Destroy this player military unit role", @player_military_unit_role, method: :delete %>
</div>